cart/urls.py
from django.urls import path
from .views import cart_detail, add_cart,remove_cart

app_name = 'cart'
urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:id>/', add_cart, name='add_cart'),
    path('remove/<int:id>/', remove_cart, name='remove_cart'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('home.urls', namespace='home')),
                  path('accounts/', include('accounts.urls', namespace='accounts')),
                  path('cart/',include('cart.urls',namespace='cart')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                           document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from home.models import *
from django.contrib.auth.models import User
from django.forms import ModelForm


class Cart(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()

    def __str__(self):
        return self.user.username


class CartForm(ModelForm):
    class Meta:
        model = Cart
        fields = ['quantity']

cart/views.py
from django.shortcuts import render, redirect
from home.models import Book
from .models import *


def cart_detail(request):
    total = 0
    cart = Cart.objects.filter(user_id=request.user.id)
    for b in cart:
        total += b.book.total_price * b.quantity
    return render(request, 'cart/cart.html', {'cart': cart, 'total': total})


def add_cart(request, id):
    url = request.META.get('HTTP_REFERER')
    book = Book.objects.get(id=id)  # اول باید ببینیم کدوم محصوله
    data = Cart.objects.filter(user_id=request.user.id, book_id=id)  # چک بشه که آیا سفارش توی سبد خرید وجود داشته؟
    if data:
        check = 'yes'
    else:
        check = 'no'
    if request.method == 'POST':
        form = CartForm(request.POST)
        if form.is_valid():
            info = form.cleaned_data['quantity']
            if check == 'yes':
                shop = Cart.objects.get(user_id=request.user.id, book_id=id)
                shop.quantity += info
                shop.save()
            else:
                Cart.objects.create(user_id=request.user.id, book_id=id, quantity=info)
        return redirect(url)  # کاربر ریدایرکت میشه به همون آدرسی که بوده


def remove_cart(request, id):
    url = request.META.get('HTTP_REFERER')
    Cart.objects.filter(id=id).delete()
    return redirect(url)

templates/cart/cart.html
{% extends 'main.html' %}
{% block body %}
    <h1>سبد خرید</h1>
    <div class="container">

        <table class="table table-dark">
            <thead>
            <th scope="col">شماره</th>
            <th scope="col">عکس</th>
            <th scope="col">کتاب</th>
            <th scope="col">تعداد</th>
            <th scope="col">قیمت</th>
            <th scope="col">قیمت نهایی</th>
            <th scope="col">حذف</th>
            </thead>
            <tbody>
            {% for c in cart %}
                <tr>
                    <th scope="col">{{ forloop.counter }}</th>
                    <td><img src="{{ c.book.image.url }}" style="width: 95px"</td>
                    <td>{{ c.book.title }}</td>
                    <td>{{ c.quantity }}</td>
                    <td>{{ c.book.unit_price }}</td>
                    <td>{% widthratio c.book.total_price 1 c.quantity %}</td>
                    <td><a href="{% url 'cart:remove_cart' c.id  %}">حذف</a></td>
                </tr>

            {% endfor %}

            <tr>
                <td colspan="6">
                    جمع کل
                </td>
                <td >
                    {{ total }}
                </td>
            </tr>

            </tbody>
        </table>

    </div>
{% endblock body %}