cart/urls.py
from django.urls import path
from .views import cart_detail, add_cart,remove_cart

app_name = 'cart'
urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:id>/', add_cart, name='add_cart'),
    path('remove/<int:id>/', remove_cart, name='remove_cart'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('home.urls', namespace='home')),
                  path('accounts/', include('accounts.urls', namespace='accounts')),
                  path('cart/',include('cart.urls',namespace='cart')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                           document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
    path('product/', views.all_product, name='product'),
    path('detail/<int:id>/', views.product_detail, name='detail'),
    path('category/<int:id>/', views.all_product, name='category'),
    path('search/', views.product_search, name='product_search')

]

home/models.py
import random

from django.db import models
from django.utils.text import slugify


class Category(models.Model):
    name = models.CharField(max_length=75,unique=True, verbose_name='نام دسته بندی')
    # slug = models.SlugField(blank=True, unique=True, allow_unicode=True, verbose_name='آدرس دسته بندی')

    # def save(self, *args, **kwargs):
    #     if not self.slug:
    #         self.slug = slugify(str(self.name) + "-" + str(random.randint(0, 400)))
    #     super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی ها '


class Book(models.Model):
    title = models.CharField(max_length=75, verbose_name='عنوان کتاب')
    author = models.CharField(max_length=75, verbose_name='نویسنده')
    # slug = models.SlugField(blank=True, allow_unicode=True, verbose_name='آدرس کتاب')
    inventory = models.PositiveIntegerField(verbose_name='تعداد')
    update = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    category = models.ManyToManyField(Category, verbose_name='دسته بندی')
    unit_price = models.IntegerField(null=True, blank=True, verbose_name='قیمت واحد')
    percent_discount = models.PositiveIntegerField(blank=True, null=True, verbose_name='تخفیف درصدی')
    cash_discount = models.PositiveIntegerField(blank=True, null=True, verbose_name='تخفیف نقدی')
    image = models.ImageField(upload_to='images')
    available = models.BooleanField(default=True, verbose_name='موجود')

    class Meta:
        verbose_name = 'کتاب'
        verbose_name_plural = 'کتاب ها'

    #
    # def save(self, *args, **kwargs):
    #     if not self.slug:
    #         self.slug = slugify(str(self.title) + "-" + str(random.randint(0, 400)))
    #     super(Book, self).save(*args, **kwargs)

    @property
    def total_price(self):
        if not self.percent_discount and not self.cash_discount:
            return self.unit_price
        elif self.percent_discount:
            total = (self.percent_discount * self.unit_price) / 100
            return int(self.unit_price - total)
        elif self.cash_discount:
            total = self.unit_price - self.cash_discount
            return int(total)
        return self.total_price

    def __str__(self):
        return self.title

home/forms.py
from django import forms


class SearchForm(forms.Form):
    search = forms.CharField(max_length=20)

home/views.py
from django.shortcuts import render

from .models import (Category,
                     Book,
                     )
from .forms import SearchForm
from django.db.models import Q
from cart.models import CartForm

def home(request):
    category = Category.objects.all()
    return render(request, 'home/home.html', {'category': category})


def all_product(request, id=None):
    books = Book.objects.all()
    form = SearchForm(request.POST)
    category = Category.objects.all()
    if 'search' in request.GET:  # اگر چیزی که کاربز سرچ کرد داخل متد گت بود:
        form = SearchForm(request.GET)
        if form.is_valid():
            data = form.cleaned_data['search']
            books = books.filter(title__exact=data)
    if id:
        data = Category.objects.get(id=id)
        books = books.filter(category=data)
    return render(request, 'home/product.html', {'books': books, 'category': category, 'form': form})


def product_detail(request, id):
    cart_form = CartForm
    book = Book.objects.get(id=id)
    return render(request, 'home/detail.html', {'book': book,'cart_form':cart_form})


def product_search(request):
    books = Book.objects.all()
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data['search']  # همون فیلدی که توی فرم هست رو باید بگیره
            if data is not None:
                books = books.filter(
                    Q(percent_discount__exact=data) | Q(unit_price__exact=data))  # میتونه بر اساس تخفیف یا قیمت سرچ کنه

            else:
                books = books.filter(title__exact=data)  # براساس اسم کتاب

            return render(request, 'home/product.html', {'books': books, 'form': form})

templates/home/detail.html
{% extends 'main.html' %}

{% block body %}
    <h1>{{ book.title }}</h1>
    <img style="width: 250px" src="{{ book.image.url }}"><br>
    <h3>{{ book.unit_price }}</h3>
    <div>
        <form method="post" action="{% url 'cart:add_cart' book.id %}">
            {% csrf_token %}
            <input type="number" name="quantity" min="1" value="1" max="{{ book.inventory }}">
            <button type="submit">اضافه کردن</button>

        </form>

    </div>

{% endblock %}

templates/home/home.html
{% extends 'main.html' %}
{% block body %}
<h1>دسته بندی ها</h1>
    {% for cat in category %}
       <a href="{% url 'home:category' cat.id %}">{{ cat.name }}</a><br>
    {% endfor %}

{% endblock %}

templates/home/product.html
{% extends 'main.html' %}
{% block body %}
    <form action="{% url 'home:product' %}" >
    {% csrf_token %}
    {{ form }}
    <button type="submit">جست و جو</button>
    </form>
    {% for book in books %}
        <h1> {{ book.title }}</h1>
        <a href="{% url 'home:detail' book.id %}">
            <img src="{{ book.image.url }}" style="width:200px">
        </a><br>
        {% if book.percent_discount or book.cash_discount %}
            <h4 style="text-decoration:line-through ">{{ book.unit_price }}</h4>
            <h3>{{ book.total_price }}</h3>
        {% else %}
            <h3>{{ book.total_price }}</h3>


        {% endif %}
    {% endfor %}
{% endblock %}