accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.user_register, name='user_register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('profile/', views.user_profile, name='profile'),
    path('update/', views.user_update, name='update'),
    path('change/', views.change_password, name='change'),
]

cart/urls.py
from django.urls import path
from .views import cart_detail, add_cart,remove_cart

app_name = 'cart'
urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:id>/', add_cart, name='add_cart'),
    path('remove/<int:id>/', remove_cart, name='remove_cart'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('home.urls', namespace='home')),
                  path('accounts/', include('accounts.urls', namespace='accounts')),
                  path('cart/',include('cart.urls',namespace='cart')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                           document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=11, null=True, blank=True)
    address = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.user.username


# با سیگنال ها بعد اینکه کاربر رجیستر کرد پروفایل رو میسازه که
# اطلاعات اضافرو خود کاربر داخل پروفایل ویرایش و اضافه کنه و وقتی کاربر رجیستر میکنه شناخته بشه پروفایلش
def save_profile_user(sender, **kwargs):
    if kwargs['created']:
        profile_user = Profile(user=kwargs['instance'])
        profile_user.save()


post_save.connect(receiver=save_profile_user, sender=User)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile


class UserRegisterForm(forms.Form):
    user_name = forms.CharField(max_length=200,
                                widget=forms.TextInput(attrs={'placeholder': 'نام کاربری'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'ایمیل'}))
    first_name = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'placeholder': 'نام'}))
    last_name = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'placeholder': 'نام خانوادگی'}))
    password_1 = forms.CharField(max_length=200,
                                 widget=forms.PasswordInput(attrs={'placeholder': 'رمزعبور'}))
    password_2 = forms.CharField(max_length=200,
                                 widget=forms.PasswordInput(attrs={'placeholder': 'تکرار رمز عبور'}))

    def clean_user_name(self):
        user = self.cleaned_data['user_name']
        if User.objects.filter(username=user).exists():
            raise forms.ValidationError('user exists!')
        return user

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('email exists!')
        return email

    def clean_password_2(self):
        password_1 = self.cleaned_data['password_1']
        password_2 = self.cleaned_data['password_2']
        if password_1 != password_2:
            raise forms.ValidationError('password not match')
        elif len(password_2) < 8:
            raise forms.ValidationError('password is too short')
        elif not any(x.isupper() for x in password_2):
            raise forms.ValidationError('password dose not have any capital character')


class UserLoginForm(forms.Form):
    user = forms.CharField()
    password = forms.CharField()


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['phone', 'address']

accounts/views.py
from django.shortcuts import render, redirect
from .forms import *
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required


def user_register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = User.objects.create_user(username=data['user_name'], email=data['email'],
                                            first_name=data['first_name'],
                                            last_name=data['last_name'], password=data['password_1'])
            user.save()
            messages.success(request, 'اکانت شما با موفقیت ساخته شد', 'success')
            return redirect('home:home')
    else:
        form = UserRegisterForm()
    context = {'form': form}
    return render(request, 'accounts/register.html', context)


def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            try:
                user = authenticate(request, username=User.objects.get(email=data['user']),
                                    password=data['password'])
            except:
                user = authenticate(request, username=data['user'], password=data['password'])
            if user is not None:
                login(request, user)
                messages.success(request, 'با موفقیت وارد شدید', 'primary')
                return redirect('home:home')
            else:
                messages.success(request, 'نام کاربری و یا پسوورد اشتباه است', 'danger')
    else:
        form = UserLoginForm()
    context = {'form': form}
    return render(request, 'accounts/login.html', context)


def user_logout(request):
    logout(request)
    messages.success(request, 'با موفقیت خارج شدید', 'warning')
    return redirect('home:home')


def user_profile(request):
    profile = Profile.objects.get(user_id=request.user.id)
    return render(request, 'accounts/profile.html', {'profile': profile})


# این فانکشن برای آپدیت پروفایل کاربر هست که دوتا فرم بهش
# داده میشه به عنوان دیتا اگر هم متد گت بود فرم با instance  ها نشون داده میشه
@login_required(login_url='accounts:login')
def user_update(request):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(request.POST, instance=request.user.profile)
        if user_form and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'به روزرسانی با موفقیت انجام شد', 'success')
            return redirect('accounts:profile')
    else:
        user_form = UserUpdateForm
        profile_form = ProfileUpdateForm(instance=request.user.profile)
        context = {'user_form': user_form, 'profile_form': profile_form}
    return render(request, 'accounts/update.html', context)


@login_required(login_url='accounts:login')
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()  # بعدش چون سشنای قبلی پاک میشن باید اوناام به روز رسانی بشن
            update_session_auth_hash(request, form.user)
            messages.success(request, 'پسوورد با موفقیت تغییر کرد')
            return redirect('accounts:profile')
        else:
            messages.error(request, 'پسوورد اشتباه است', 'danger')
            return redirect('accounts:change')
    else:
        form = PasswordChangeForm(request.user)  # درخواست از طرف کدوم یوزر هست

    return render(request, 'accounts/change.html', {'form': form})

templates/accounts/change.html
{% extends 'main.html' %}
{% block body %}
    <h1>change password</h1>
    <form method="post">
        {% csrf_token %}
        <input type="password" name="old_password" placeholder="پسورد قدیمی"><br><br>
        <input type="password" name="new_password1" placeholder="پسورد جدید"><br><br>
        <input type="password" name="new_password2" placeholder="تکرار پسوورد جدید"><br><br>

        <button type="submit">ثبت تغییرات</button>

    </form>
    <style>
        form ul{
            display: none;
        }
    </style>
{% endblock body %}

templates/accounts/login.html
{% extends 'main.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'accounts/login.css' %}">{% endblock %}

{% block body %}
    <form method="post">
        {% csrf_token %}
        <input type="text" name="user" placeholder="نام کاربری"><br><br>
        <input type="password" name="password" placeholder="رمز عبور" ><br><br>
        <button type="submit"> ورود </button>
    </form>
{% endblock %}

templates/accounts/profile.html
{% extends 'main.html' %}

{% block title %}
{% endblock title %}
{% block body %}
    <div class="card" style="width: 18rem;">
        <div class="card-body">

            <h6 class="card-subtitle mb-2 text-muted"> user: {{ profile.user.username }} </h6>
            <h6 class="card-subtitle mb-2 text-muted"> name : {{ profile.user.first_name }} </h6>
            <h6 class="card-subtitle mb-2 text-muted">lastname: {{ profile.user.last_name }} </h6>
            <h6 class="card-subtitle mb-2 text-muted"> email: {{ profile.user.email }} </h6>
            <h6 class="card-subtitle mb-2 text-muted"> phone: {{ profile.phone }} </h6>

            <a href="{% url 'accounts:update' %}">ویرایش پروفایل</a><br>
            <a href="{% url 'accounts:change' %}">تغییر رمز عبور</a>
        </div>
    </div>

{% endblock %}
<table>
    <tr>
        <th>user: {{ profile.user.username }}</th>
    </tr>
    <tr>
        <th>name : {{ profile.user.first_name }} </th>
    </tr>
    <tr>
        <th>lastname: {{ profile.user.last_name }} </th>
    </tr>
    <tr>
        <th>email: {{ profile.user.email }}</th>
    </tr>
    <tr>
        <th>phone: {{ profile.phone }}</th>
    </tr>
</table>

templates/accounts/register.html
{% extends 'main.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'accounts/register.css' %}">{% endblock %}
{% block body %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">ثبت </button>
    </form>

{% endblock body %}

templates/accounts/update.html
{% extends 'main.html' %}

{% block body %}
   <h1>profile update</h1>
    <form method="post" action="">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <button type="submit">update</button>
    </form>
{% endblock %}