accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.user_register, name='user_register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('profile/', views.user_profile, name='profile'),
    path('update/', views.user_update, name='update'),
    path('change/', views.change_password, name='change'),
]

cart/urls.py
from django.urls import path
from .views import cart_detail, add_cart,remove_cart

app_name = 'cart'
urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:id>/', add_cart, name='add_cart'),
    path('remove/<int:id>/', remove_cart, name='remove_cart'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('home.urls', namespace='home')),
                  path('accounts/', include('accounts.urls', namespace='accounts')),
                  path('cart/',include('cart.urls',namespace='cart')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                           document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
    path('product/', views.all_product, name='product'),
    path('detail/<int:id>/', views.product_detail, name='detail'),
    path('category/<int:id>/', views.all_product, name='category'),
    path('search/', views.product_search, name='product_search')

]

templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    {% block css %}{% endblock %}
    <title>Title</title>
</head>
<body>

{% include 'navbar.html' %}
{% include 'message.html' %}
{% block body %}
{% endblock %}

</body>
</html>

templates/message.html
{% if messages %}
    {% for msg in messages %}
        <h3 {% if msg.tags %}class="alert alert-{{ msg.tags }}" {% endif %}> {{ msg }} </h3>
    {% endfor %}
{% endif %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link " href="{% url 'home:home' %}">خانه</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link " href="{% url 'home:product' %}">کتاب ها</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}"> خروج</a>
                </li>
                 <li class="nav-item">
                    <a class="nav-link" href="{% url 'cart:cart_detail' %}"> سبد خرید</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:profile' %}"> پروفایل</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">ورود</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:user_register' %}">ثبت نام</a>
                </li>
            {% endif %}

        </ul>
    </div>
</nav>